// 시드 — 프론트엔드 products.ts 와 동일한 주스 7종을 DB에 채운다.
// 실행: npm run seed  (DATABASE_URL 필요)
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const BASE = "/Drink-E-commerce"

const products = [
  {
    id: "fruits1-1",
    category: "fruits",
    slug: "apple",
    image: `${BASE}/images/apple.jpg`,
    images: [`${BASE}/images/apple.jpg`, `${BASE}/images/apple_menu.jpg`],
    price: 550,
    volume: "250ml",
    origin: "日本（青森県）",
    expiry: "製造より240日",
    jan: "312312313",
    energy: "39.6kcal",
    protein: "0.8g",
    fat: "0.0g",
    carbs: "9.1g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🍎りんご", ko: "U ma!Fruits 🍎사과", en: "U ma!Fruits 🍎Apple" },
    flavor: { ja: "りんご", ko: "사과", en: "Apple" },
    description: {
      ja: "青森県産の新鮮なりんごを使用した、甘みと酸味のバランスが絶妙なジュースです。無加熱製法で素材本来の風味をそのままお届けします。",
      ko: "청주현산 신선한 사과를 사용한, 단맛과 산미의 균형이 절묘한 주스입니다. 무가열 공법으로 소재 본연의 풍미를 그대로 전달합니다.",
      en: "Made from fresh Aomori apples, this juice has a perfect balance of sweetness and acidity. Our raw process preserves the original flavor.",
    },
    tags: ["fruits", "apple", "100% juice"],
    isNew: false,
  },
  {
    id: "fruits1-2",
    category: "fruits",
    slug: "watermelon",
    image: `${BASE}/images/watermelon.jpg`,
    images: [`${BASE}/images/watermelon.jpg`, `${BASE}/images/water_menu.jpg`],
    price: 580,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より180日",
    jan: "312312314",
    energy: "25.0kcal",
    protein: "0.5g",
    fat: "0.0g",
    carbs: "6.0g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🍉スイカ", ko: "U ma!Fruits 🍉수박", en: "U ma!Fruits 🍉Watermelon" },
    flavor: { ja: "スイカ", ko: "수박", en: "Watermelon" },
    description: {
      ja: "夏の定番、みずみずしいスイカを丸ごとしぼったジュース。清涼感あふれる甘さが特徴です。",
      ko: "여름의 대명사, 싱그러운 수박을 통째로 착즙한 주스. 청량감 넘치는 달콤함이 특징입니다.",
      en: "Whole watermelon pressed juice — refreshingly sweet, perfect for summer.",
    },
    tags: ["fruits", "watermelon", "seasonal"],
    isNew: true,
  },
  {
    id: "fruits1-3",
    category: "fruits",
    slug: "orange",
    image: `${BASE}/images/orenji.jpg`,
    images: [`${BASE}/images/orenji.jpg`, `${BASE}/images/orenji_menu.jpg`],
    price: 520,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より200日",
    jan: "312312315",
    energy: "45.0kcal",
    protein: "0.7g",
    fat: "0.0g",
    carbs: "10.5g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🍊オレンジ", ko: "U ma!Fruits 🍊오렌지", en: "U ma!Fruits 🍊Orange" },
    flavor: { ja: "オレンジ", ko: "오렌지", en: "Orange" },
    description: {
      ja: "ビタミンCたっぷりの国産オレンジをそのまま絞ったフレッシュジュース。爽やかな香りが広がります。",
      ko: "비타민C 풍부한 국산 오렌지를 그대로 짜낸 신선한 주스. 상쾌한 향기가 퍼집니다.",
      en: "Freshly squeezed domestic oranges, rich in Vitamin C with a refreshing aroma.",
    },
    tags: ["fruits", "orange", "vitamin C"],
  },
  {
    id: "fruits1-4",
    category: "fruits",
    slug: "grape",
    image: `${BASE}/images/fudou.jpg`,
    images: [`${BASE}/images/fudou.jpg`, `${BASE}/images/fudouu.jpg`],
    price: 600,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より210日",
    jan: "312312316",
    energy: "58.0kcal",
    protein: "0.4g",
    fat: "0.0g",
    carbs: "14.0g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🍇ブドウ", ko: "U ma!Fruits 🍇포도", en: "U ma!Fruits 🍇Grape" },
    flavor: { ja: "ブドウ", ko: "포도", en: "Grape" },
    description: {
      ja: "濃厚な甘みと深い紫色が魅力の国産ブドウジュース。ポリフェノールが豊富です。",
      ko: "진한 달콤함과 깊은 보랏빛이 매력인 국산 포도 주스. 폴리페놀이 풍부합니다.",
      en: "Rich, dark grape juice packed with polyphenols and natural sweetness.",
    },
    tags: ["fruits", "grape", "polyphenol"],
    isSale: true,
    salePrice: 480,
  },
  {
    id: "vege2-1",
    category: "vegetables",
    slug: "carrot",
    image: `${BASE}/images/carrot.jpg`,
    images: [`${BASE}/images/carrot.jpg`, `${BASE}/images/carrt_menu.jpg`],
    price: 520,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より180日",
    jan: "312312320",
    energy: "36.0kcal",
    protein: "0.6g",
    fat: "0.0g",
    carbs: "8.4g",
    salt: "0.08g",
    name: { ja: "U ma!Fruits 🥕人参", ko: "U ma!Fruits 🥕당근", en: "U ma!Fruits 🥕Carrot" },
    flavor: { ja: "人参", ko: "당근", en: "Carrot" },
    description: {
      ja: "βカロテン豊富な国産人参を使用したベジタブルジュース。自然な甘みと栄養たっぷりです。",
      ko: "베타카로틴 풍부한 국산 당근을 사용한 채소 주스. 자연스러운 달콤함과 영양이 가득합니다.",
      en: "Vegetable juice made from β-carotene rich domestic carrots — naturally sweet and nutritious.",
    },
    tags: ["vegetables", "carrot", "beta-carotene"],
  },
  {
    id: "vege2-2",
    category: "vegetables",
    slug: "tomato",
    image: `${BASE}/images/tomato.jpg`,
    images: [`${BASE}/images/tomato.jpg`, `${BASE}/images/tomato_menu.jpg`],
    price: 500,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より200日",
    jan: "312312321",
    energy: "19.0kcal",
    protein: "0.7g",
    fat: "0.0g",
    carbs: "4.0g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🍅トマト", ko: "U ma!Fruits 🍅토마토", en: "U ma!Fruits 🍅Tomato" },
    flavor: { ja: "トマト", ko: "토마토", en: "Tomato" },
    description: {
      ja: "リコピンたっぷりの完熟トマトをそのまま絞ったジュース。無塩で素材の旨みを最大限に引き出しました。",
      ko: "리코펜 풍부한 완숙 토마토를 그대로 착즙한 주스. 무염으로 소재의 감칠맛을 최대한 끌어냈습니다.",
      en: "100% ripe tomato juice packed with lycopene, no salt added to maximize natural umami.",
    },
    tags: ["vegetables", "tomato", "lycopene"],
    isNew: true,
  },
  {
    id: "vege2-3",
    category: "vegetables",
    slug: "paprika",
    image: `${BASE}/images/paprika.jpg`,
    images: [`${BASE}/images/paprika.jpg`, `${BASE}/images/paprika_menu.jpg`],
    price: 560,
    volume: "250ml",
    origin: "日本",
    expiry: "製造より180日",
    jan: "312312322",
    energy: "22.0kcal",
    protein: "0.9g",
    fat: "0.0g",
    carbs: "5.1g",
    salt: "0.00g",
    name: { ja: "U ma!Fruits 🫑パプリカ", ko: "U ma!Fruits 🫑파프리카", en: "U ma!Fruits 🫑Paprika" },
    flavor: { ja: "パプリカ", ko: "파프리카", en: "Paprika" },
    description: {
      ja: "鮮やかな彩りと豊富なビタミンCを誇るパプリカジュース。甘みとほのかな苦みが絶妙に調和しています。",
      ko: "선명한 색감과 풍부한 비타민C를 자랑하는 파프리카 주스. 달콤함과 은은한 쓴맛이 절묘하게 조화를 이룹니다.",
      en: "Vibrant paprika juice, rich in Vitamin C with a delightful blend of sweetness and mild bitterness.",
    },
    tags: ["vegetables", "paprika", "vitamin C"],
    isSale: true,
    salePrice: 440,
  },
]

async function main() {
  for (const p of products) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: p,
      create: p,
    })
  }
  console.log(`✅ seeded ${products.length} products`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
